### ISSUE TITLE
Problem with fstd2nc on ppp3

### ISSUE THREAD

**Issue by guziy** [neishm/fstd2nc#21] opened 2019-12-16 22:00 UTC
Hi:

We are having this weird issue with `fstd2nc` on `ppp3`:

Somehow a float or something else, not compatible with bitwise_and, creeps into the lists...
Maybe some kind of forced cast to int is required before the key is generated.

```
+ /fs/site3/eccc/cmd/n/gud001/maestro_hubs/c3s_exp/work/20160501000000/c3shcast_module/loop_ens/dailyinst_task+4/bin/fstd2nc -f --nc-format NETCDF3_CLASSIC /space/hall3/sitestore/eccc/cmd/n/gud001/c3s/moutput_gemnemo_hindcast/NETCDF/2016/05/ens_05//GEM-NEMO_day_GL_2016_05_5_1b1deg /space/hall3/sitestore/eccc/cmd/n/gud001/c3s/moutput_gemnemo_hindcast/NETCDF/2016/05/ens_05//cwao_GEM-NEMO-v20190731_hindcast_S2016050101_ocean_day_surface_sic_r05i01p01_tmp.nc3
Traceback (most recent call last):
  File "/fs/site3/eccc/cmd/n/gud001/maestro_hubs/c3s_exp/work/20160501000000/c3shcast_module/loop_ens/dailyinst_task+4/bin/fstd2nc", line 11, in <module>
    load_entry_point('fstd2nc==0.20190903.0', 'console_scripts', 'fstd2nc')()
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/master/fstd2nc_0.20190903.0_all/lib/python/fstd2nc/__main__.py", line 107, in _fstd2nc_cmdline_trapped
    _fstd2nc_cmdline (*args, **kwargs)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/master/fstd2nc_0.20190903.0_all/lib/python/fstd2nc/__main__.py", line 64, in _fstd2nc_cmdline
    buf = buffer_type(infiles, **args)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/master/fstd2nc_0.20190903.0_all/lib/python/fstd2nc/__init__.py", line 62, in __init__
    super(Buffer,self).__init__(filename, *args,**kwargs)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/master/fstd2nc_0.20190903.0_all/lib/python/fstd2nc/mixins/netcdf.py", line 143, in __init__
    super(netCDF_IO,self).__init__(*args,**kwargs)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/master/fstd2nc_0.20190903.0_all/lib/python/fstd2nc/mixins/netcdf.py", line 93, in __init__
    super(netCDF_Atts,self).__init__(*args,**kwargs)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/master/fstd2nc_0.20190903.0_all/lib/python/fstd2nc/mixins/removestuff.py", line 49, in __init__
    super(RemoveStuff,self).__init__(*args,**kwargs)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/master/fstd2nc_0.20190903.0_all/lib/python/fstd2nc/mixins/filter.py", line 46, in __init__
    super(FilterRecords,self).__init__(*args,**kwargs)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/master/fstd2nc_0.20190903.0_all/lib/python/fstd2nc/mixins/xycoords.py", line 326, in __init__
    super(XYCoords,self).__init__(*args,**kwargs)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/master/fstd2nc_0.20190903.0_all/lib/python/fstd2nc/mixins/vcoords.py", line 92, in __init__
    super(VCoords,self).__init__(*args,**kwargs)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/master/fstd2nc_0.20190903.0_all/lib/python/fstd2nc/mixins/series.py", line 97, in __init__
    super(Series,self).__init__(*args,**kwargs)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/master/fstd2nc_0.20190903.0_all/lib/python/fstd2nc/mixins/ensembles.py", line 46, in __init__
    super(Ensembles,self).__init__(*args,**kwargs)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/master/fstd2nc_0.20190903.0_all/lib/python/fstd2nc/mixins/dates.py", line 81, in __init__
    super(Dates,self).__init__(*args,**kwargs)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/master/fstd2nc_0.20190903.0_all/lib/python/fstd2nc/mixins/masks.py", line 41, in __init__
    super(Masks,self).__init__(*args,**kwargs)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/master/fstd2nc_0.20190903.0_all/lib/python/fstd2nc/mixins/select.py", line 42, in __init__
    super(SelectVars,self).__init__(*args,**kwargs)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/master/fstd2nc_0.20190903.0_all/lib/python/fstd2nc/mixins/__init__.py", line 448, in __init__
    params = all_params(funit,out=h)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/master/fstd2nc_0.20190903.0_all/lib/python/fstd2nc/extra.py", line 335, in all_params
    out['key'][:] = (np.array(file_index_list)&0x3FF) | ((np.array(recno_list)&0x1FF)<<10) | ((np.array(pageno_list)&0xFFF)<<19)
TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

```
(cdo-1.9.2) eccc-ppp3:~/.suites/cansips/main>fstd2nc --version
0.20190903.0
```
Thanks

**Comment by neishm** [comment] 2019-12-17 02:01
Hi @guziy,

Thanks for filing the bug report.  It looks like there's some weird problem in the logic for quickly calculating keys.  I'll see if I can pinpoint the source of the bug.  As a possible workaround, you could try the `--no-quick-scan` option, which gets the keys a different way.

I'm trying to reproduce the error, but I'm unable to find the input file (`/space/hall3/sitestore/eccc/cmd/n/gud001/c3s/moutput_gemnemo_hindcast/NETCDF/2016/05/ens_05//GEM-NEMO_day_GL_2016_05_5_1b1deg`).  Is there another file that triggers the same problem, that could be used for testing?

**Comment by guziy** [comment] 2019-12-17 13:33
Hi @neishm:

I asked my colleague not to touch that file...
We will find a case for you today.

Thanks

**Comment by gulilat-diro** [comment] 2020-01-06 15:06
Dear neishm, Sasha,
Thanks for your prompt reply and help. While I try to reproduce the above error, I reckon that there was a 'rm -f  ...' statement in another script which is running in parallel but (wrongly) removes the above file at various stage.  Fixing this bug solves my problem. 

cheers,
Gulilat

**Comment by neishm** [comment] 2020-01-06 18:42
Hi @gulilat-diro and @guziy,

I'm glad there was a resolution to this problem.  From what I understand, there's no updates needed in the fstd2nc code, just in the calling scripts?  I'm going to close this issue as "resolved" for now, but please feel free to re-open if the problem resurfaces.

Thanks,
Mike

**Closed by neishm** 2020-01-06 18:42 UTC
